package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io/ioutil"
	"log"
	"strings"
	"text/template"
)

// Routes represents the schema for a routes.json file. It has many routes.
type Routes struct {
	Routes []Route `json:"routes"`
}

// Route is a single instance of a route in a routes.json file. It has
// informatino about the endpoint and the service that handles each type of
// request.
type Route struct {
	Endpoint string   `json:"endpoint"`
	Service  string   `json:"service"`
	Methods  []Method `json:"methods"`
}

func (r Route) String() string {
	methods := []string{}
	for _, method := range r.Methods {
		methods = append(methods, method.Method)
	}
	return fmt.Sprintf("%s (%s)", r.Endpoint, strings.Join(methods, ", "))
}

// MountFunctionName generates the name of the "mount" function used to add the
// handler to a mux routes.
func (r Route) MountFunctionName() string {
	parts := strings.Split(r.Service, ".")
	name := parts[len(parts)-1]
	return fmt.Sprintf("Mount%s", name)
}

// ServiceContractName generates the name of the interface that defines all of
// the methods that a service is required to have in order to meet the
// requirements defined in the routes.json file.
func (r Route) ServiceContractName() string {
	parts := strings.Split(r.Service, ".")
	name := parts[len(parts)-1]
	return fmt.Sprintf("%sContract", name)
}

// Method is a badly named data structure that hold information that is unique
// to an http method for a given route. This includes the method itself (GET,
// POST, etc.), the name of the handlers, and types for the input and the
// output of the handler.
type Method struct {
	Method   string `json:"method"`
	Handler  string `json:"handler"`
	Request  string `json:"request"`
	Response string `json:"response"`
}

// Signature generates a string that is the method defintion of this Method.
func (m Method) Signature() string {
	request := "url.Values"
	if m.Request != "" {
		request = "*" + m.Request
	}

	return fmt.Sprintf("%s(ctx context.Context, req %s) (*%s, error)",
		m.Handler, request, m.Response)
}

var (
	routesPath = flag.String("routes", "routes.json", "Path to routes definitions file.")
	outputPath = flag.String("output", ".", "Path to output directory.")

	funcs = template.FuncMap{
		"stripPackage": stripPackage,
	}

	handlerTmpl = template.Must(template.New("handler").Funcs(funcs).Parse(`
// Code generated by generator/mount/main.go. DO NOT EDIT.
package mount

import (
	"context"
	"encoding/json"
	"io/ioutil"
	"log"
	"net/http"
	"net/url"
	"os"

	"github.com/gorilla/mux"
	"github.com/gorilla/sessions"

	"github.com/minond/captainslog/server/model"
	"github.com/minond/captainslog/server/service"
)

var store = sessions.NewCookieStore([]byte(os.Getenv("SESSION_KEY")))

{{range .Routes}}
{{with $route := .}}
// {{.ServiceContractName}} defines what an implementation of {{.Service}}
// should look like. This interface is derived from the routes.json file
// provided as input to this generator, and it is a combination of the handler,
// the request, and the response.
type {{.ServiceContractName}} interface {
{{- range .Methods}}
	// {{.Handler}} runs when a {{.Method}} {{$route.Endpoint}} request comes in.
	{{.Signature}}
{{end}}
}
{{end}}
{{end}}

{{range .Routes}}
// {{.MountFunctionName}} add a handler to a Gorilla Mux Router that will route
// an incoming request through the {{.Service | stripPackage}} service.
func {{.MountFunctionName}}(router *mux.Router, serv {{.ServiceContractName}}) {
	log.Print("[INFO] mounting {{.Service}} on {{.Endpoint}} endpoint")
	router.HandleFunc("{{.Endpoint}}", func(w http.ResponseWriter, r *http.Request) {
		log.Printf("[INFO] handling %s %s request", r.Method, r.URL.String())

		session, err := store.Get(r, "main")
		if err != nil {
			http.Error(w, "unable to read request data", http.StatusInternalServerError)
			log.Printf("[ERROR] error getting session: %v", err)
			return
		}

		switch r.Method {
		{{range .Methods}}
		case "{{.Method}}":
			{{- if not .Request}}
			req := r.URL.Query()
			{{else}}
			defer r.Body.Close()
			data, err := ioutil.ReadAll(r.Body)
			if err != nil {
				http.Error(w, "unable to read request body", http.StatusBadRequest)
				log.Printf("[ERROR] error reading request body: %v", err)
				return
			}

			req := &{{.Request}}{}
			if err = json.Unmarshal(data, req); err != nil {
				http.Error(w, "unable to decode request", http.StatusBadRequest)
				log.Printf("[ERROR] error unmarshaling request: %v", err)
				return
			}
			{{end}}

			ctx := context.Background()
			for key, val := range session.Values {
				ctx = context.WithValue(ctx, key, val)
			}

			res, err := serv.{{.Handler}}(ctx, req)
			if err != nil {
				http.Error(w, "unable to handle request", http.StatusInternalServerError)
				log.Printf("[ERROR] error handling request: %v", err)
				return
			}

			out, err := json.Marshal(res)
			if err != nil {
				http.Error(w, "unable to encode response", http.StatusInternalServerError)
				log.Printf("[ERROR] error marshaling response: %v", err)
				return
			}

			w.Write(out)
		{{end}}

		default:
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		}
	})
}
{{end}}
`))
)

func init() {
	flag.Parse()
	log.SetFlags(0)
}

func main() {
	data, err := ioutil.ReadFile(*routesPath)
	if err != nil {
		log.Fatalf("error reading routes file: %v", err)
	}

	routes := &Routes{}
	json.Unmarshal(data, routes)

	buff := &bytes.Buffer{}
	if err = handlerTmpl.Execute(buff, routes); err != nil {
		log.Fatalf("error generating template: %v", err)
	}

	for _, route := range routes.Routes {
		log.Printf("generating %s", route.String())
	}

	unformatted := buff.Bytes()
	contents, err := format.Source(unformatted)
	if err != nil {
		log.Fatalf("error formatting contents: %v", err)
	}

	if err = ioutil.WriteFile(*outputPath, contents, 0644); err != nil {
		log.Fatalf("error writing to file: %v", err)
	}
	log.Printf("wrote %d bytes to %s", len(contents), *outputPath)
}

func stripPackage(input string) string {
	parts := strings.SplitN(input, ".", 2)
	return parts[1]
}
