// Code generated by "stringer -type=QueryType"; DO NOT EDIT.

package sqlparse

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SelectQuery-0]
}

const _QueryType_name = "SelectQuery"

var _QueryType_index = [...]uint8{0, 11}

func (i QueryType) String() string {
	if i < 0 || i >= QueryType(len(_QueryType_index)-1) {
		return "QueryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QueryType_name[_QueryType_index[i]:_QueryType_index[i+1]]
}
