// Code generated by protoc-gen-typescript-definitions. DO NOT EDIT.
// source: book.proto

export type Book = {
  guid?: string
  name?: string
  grouping?: number
  extractor?: Array<{
    guid?: string
    label?: string
    match?: string
  }>
}
