// Code generated by protoc-gen-typescript-definitions. DO NOT EDIT.
// source: collection.proto

export type Collection = {
  entry?: Array<{
    guid?: string
    text?: string
    timestamp?: number
    data?: Map<string, string>
  }>
}
