// Code generated by "stringer -type=logicalOp"; DO NOT EDIT.

package query

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[and-0]
	_ = x[or-1]
}

const _logicalOp_name = "andor"

var _logicalOp_index = [...]uint8{0, 3, 5}

func (i logicalOp) String() string {
	if i >= logicalOp(len(_logicalOp_index)-1) {
		return "logicalOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _logicalOp_name[_logicalOp_index[i]:_logicalOp_index[i+1]]
}
