// Code generated by "stringer -type=tok"; DO NOT EDIT.

package query

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokInvalid-0]
	_ = x[tokCloseParenthesis-1]
	_ = x[tokComma-2]
	_ = x[tokDiv-3]
	_ = x[tokEq-4]
	_ = x[tokGe-5]
	_ = x[tokGt-6]
	_ = x[tokLe-7]
	_ = x[tokLt-8]
	_ = x[tokMinus-9]
	_ = x[tokMul-10]
	_ = x[tokOpenParenthesis-11]
	_ = x[tokPeriod-12]
	_ = x[tokPlus-13]
	_ = x[tokDoubleQuoteString-14]
	_ = x[tokIdentifier-15]
	_ = x[tokNumber-16]
	_ = x[tokSingleQuoteString-17]
}

const _tok_name = "tokInvalidtokCloseParenthesistokCommatokDivtokEqtokGetokGttokLetokLttokMinustokMultokOpenParenthesistokPeriodtokPlustokDoubleQuoteStringtokIdentifiertokNumbertokSingleQuoteString"

var _tok_index = [...]uint8{0, 10, 29, 37, 43, 48, 53, 58, 63, 68, 76, 82, 100, 109, 116, 136, 149, 158, 178}

func (i tok) String() string {
	if i < 0 || i >= tok(len(_tok_index)-1) {
		return "tok(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tok_name[_tok_index[i]:_tok_index[i+1]]
}
