// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entry.proto

package log

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entry struct {
	Guid                 string            `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Text                 string            `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedOn            int64             `protobuf:"varint,4,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	CreatedBy            string            `protobuf:"bytes,5,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedOn            int64             `protobuf:"varint,6,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	UpdatedBy            string            `protobuf:"bytes,7,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	DeletedOn            int64             `protobuf:"varint,8,opt,name=deletedOn,proto3" json:"deletedOn,omitempty"`
	DeletedBy            string            `protobuf:"bytes,9,opt,name=deletedBy,proto3" json:"deletedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_3b49cf501252504e, []int{0}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (dst *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(dst, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Entry) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Entry) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Entry) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *Entry) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Entry) GetUpdatedOn() int64 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

func (m *Entry) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *Entry) GetDeletedOn() int64 {
	if m != nil {
		return m.DeletedOn
	}
	return 0
}

func (m *Entry) GetDeletedBy() string {
	if m != nil {
		return m.DeletedBy
	}
	return ""
}

type EntryCreateRequest struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	CreatedOn            int64    `protobuf:"varint,3,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	UpdatedOn            int64    `protobuf:"varint,4,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryCreateRequest) Reset()         { *m = EntryCreateRequest{} }
func (m *EntryCreateRequest) String() string { return proto.CompactTextString(m) }
func (*EntryCreateRequest) ProtoMessage()    {}
func (*EntryCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_3b49cf501252504e, []int{1}
}
func (m *EntryCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryCreateRequest.Unmarshal(m, b)
}
func (m *EntryCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryCreateRequest.Marshal(b, m, deterministic)
}
func (dst *EntryCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryCreateRequest.Merge(dst, src)
}
func (m *EntryCreateRequest) XXX_Size() int {
	return xxx_messageInfo_EntryCreateRequest.Size(m)
}
func (m *EntryCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EntryCreateRequest proto.InternalMessageInfo

func (m *EntryCreateRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *EntryCreateRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *EntryCreateRequest) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *EntryCreateRequest) GetUpdatedOn() int64 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

type EntryCreateResponse struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Entry                *Entry   `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryCreateResponse) Reset()         { *m = EntryCreateResponse{} }
func (m *EntryCreateResponse) String() string { return proto.CompactTextString(m) }
func (*EntryCreateResponse) ProtoMessage()    {}
func (*EntryCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_3b49cf501252504e, []int{2}
}
func (m *EntryCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryCreateResponse.Unmarshal(m, b)
}
func (m *EntryCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryCreateResponse.Marshal(b, m, deterministic)
}
func (dst *EntryCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryCreateResponse.Merge(dst, src)
}
func (m *EntryCreateResponse) XXX_Size() int {
	return xxx_messageInfo_EntryCreateResponse.Size(m)
}
func (m *EntryCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EntryCreateResponse proto.InternalMessageInfo

func (m *EntryCreateResponse) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *EntryCreateResponse) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func init() {
	proto.RegisterType((*Entry)(nil), "log.Entry")
	proto.RegisterMapType((map[string]string)(nil), "log.Entry.DataEntry")
	proto.RegisterType((*EntryCreateRequest)(nil), "log.EntryCreateRequest")
	proto.RegisterType((*EntryCreateResponse)(nil), "log.EntryCreateResponse")
}

func init() { proto.RegisterFile("entry.proto", fileDescriptor_entry_3b49cf501252504e) }

var fileDescriptor_entry_3b49cf501252504e = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x3f, 0x4f, 0xb4, 0x40,
	0x10, 0xc6, 0xc3, 0x2d, 0xdc, 0xfb, 0x32, 0x58, 0x98, 0xf5, 0x12, 0x37, 0x17, 0x0b, 0x42, 0x45,
	0x45, 0x81, 0x85, 0x46, 0x3b, 0xd4, 0xea, 0x0a, 0x13, 0xfc, 0x04, 0xeb, 0x31, 0x21, 0x17, 0x09,
	0x20, 0x2c, 0x97, 0xe3, 0x0b, 0xfa, 0xb9, 0xcc, 0xce, 0x12, 0xfe, 0xe8, 0x15, 0x76, 0xb3, 0xbf,
	0x67, 0x9f, 0x1d, 0xe6, 0x61, 0xc0, 0xc3, 0x52, 0x35, 0x7d, 0x54, 0x37, 0x95, 0xaa, 0x38, 0x2b,
	0xaa, 0x3c, 0xf8, 0x5a, 0x81, 0xf3, 0xa2, 0x21, 0xe7, 0x60, 0xe7, 0xdd, 0x21, 0x13, 0x96, 0x6f,
	0x85, 0x6e, 0x4a, 0xb5, 0x66, 0x0a, 0x4f, 0x4a, 0xac, 0x0c, 0xd3, 0x35, 0x0f, 0xc1, 0xce, 0xa4,
	0x92, 0x82, 0xf9, 0x2c, 0xf4, 0xe2, 0x4d, 0x54, 0x54, 0x79, 0x44, 0x2f, 0x44, 0xcf, 0x52, 0x49,
	0xaa, 0x52, 0xba, 0xc1, 0x6f, 0xc0, 0xdd, 0x37, 0x28, 0x15, 0x66, 0xaf, 0xa5, 0xb0, 0x7d, 0x2b,
	0x64, 0xe9, 0x04, 0x66, 0x6a, 0xd2, 0x0b, 0x87, 0x1a, 0x4c, 0x40, 0xab, 0x5d, 0x9d, 0x0d, 0xde,
	0xb5, 0xf1, 0x8e, 0x60, 0xa6, 0x26, 0xbd, 0xf8, 0x67, 0xbc, 0x23, 0xd0, 0x6a, 0x86, 0x05, 0x1a,
	0xef, 0x7f, 0xe3, 0x1d, 0xc1, 0x4c, 0x4d, 0x7a, 0xe1, 0x1a, 0xef, 0x08, 0xb6, 0x77, 0xe0, 0x8e,
	0x63, 0xf0, 0x4b, 0x60, 0x1f, 0xd8, 0x0f, 0x89, 0xe8, 0x92, 0x6f, 0xc0, 0x39, 0xca, 0xa2, 0xc3,
	0x21, 0x11, 0x73, 0x78, 0x58, 0xdd, 0x5b, 0xc1, 0x09, 0x38, 0x99, 0x9e, 0x68, 0x84, 0x14, 0x3f,
	0x3b, 0x6c, 0xd5, 0x9f, 0x43, 0x5d, 0x44, 0xc5, 0xce, 0x44, 0x35, 0x85, 0x61, 0xff, 0x08, 0x23,
	0xd8, 0xc1, 0xd5, 0xa2, 0x73, 0x5b, 0x57, 0x65, 0x8b, 0x67, 0x5b, 0xfb, 0xe0, 0xd0, 0x06, 0x50,
	0x6f, 0x2f, 0x86, 0xe9, 0xe7, 0xa5, 0x46, 0x88, 0x77, 0x70, 0x41, 0xe7, 0x37, 0x6c, 0x8e, 0x87,
	0x3d, 0xf2, 0x47, 0x58, 0x9b, 0x77, 0xf9, 0xf5, 0x74, 0x79, 0x31, 0xe3, 0x56, 0xfc, 0x16, 0xcc,
	0x27, 0xbc, 0xaf, 0x69, 0xd1, 0x6e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x33, 0x48, 0x68,
	0x77, 0x02, 0x00, 0x00,
}
