// Code generated by protoc-gen-go. DO NOT EDIT.
// source: group.proto

package log

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Group struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Entry                []*Entry `protobuf:"bytes,2,rep,name=entry,proto3" json:"entry,omitempty"`
	CreatedOn            int64    `protobuf:"varint,3,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	CreatedBy            string   `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedOn            int64    `protobuf:"varint,5,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,6,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_group_bfe08fc56fb7e6ab, []int{0}
}
func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (dst *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(dst, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Group) GetEntry() []*Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *Group) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *Group) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Group) GetUpdatedOn() int64 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

func (m *Group) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func init() {
	proto.RegisterType((*Group)(nil), "log.Group")
}

func init() { proto.RegisterFile("group.proto", fileDescriptor_group_bfe08fc56fb7e6ab) }

var fileDescriptor_group_bfe08fc56fb7e6ab = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2f, 0xca, 0x2f,
	0x2d, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0xc9, 0x4f, 0x97, 0xe2, 0x4e, 0xcd,
	0x2b, 0x29, 0xaa, 0x84, 0x88, 0x28, 0x6d, 0x65, 0xe4, 0x62, 0x75, 0x07, 0xa9, 0x10, 0x12, 0xe2,
	0x62, 0x49, 0x2f, 0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x14,
	0xb8, 0x58, 0xc1, 0x8a, 0x25, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0xb8, 0xf4, 0x72, 0xf2, 0xd3,
	0xf5, 0x5c, 0x41, 0x22, 0x41, 0x10, 0x09, 0x21, 0x19, 0x2e, 0xce, 0xe4, 0xa2, 0xd4, 0xc4, 0x92,
	0xd4, 0x14, 0xff, 0x3c, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x84, 0x00, 0x92, 0xac, 0x53,
	0xa5, 0x04, 0x0b, 0xd8, 0x60, 0x84, 0x00, 0x48, 0xb6, 0xb4, 0x20, 0x05, 0xaa, 0x97, 0x15, 0xa2,
	0x17, 0x2e, 0x80, 0x24, 0xeb, 0x54, 0x29, 0xc1, 0x06, 0xd1, 0x0b, 0x17, 0x48, 0x62, 0x03, 0x3b,
	0xdf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x29, 0x3b, 0xa7, 0xdf, 0x00, 0x00, 0x00,
}
