// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package log

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Log struct {
	Guid                 string            `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Text                 string            `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedOn            int64             `protobuf:"varint,4,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	CreatedBy            string            `protobuf:"bytes,5,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedOn            int64             `protobuf:"varint,6,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	UpdatedBy            string            `protobuf:"bytes,7,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	DeletedOn            int64             `protobuf:"varint,8,opt,name=deletedOn,proto3" json:"deletedOn,omitempty"`
	DeletedBy            string            `protobuf:"bytes,9,opt,name=deletedBy,proto3" json:"deletedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_7db29dfae25f4450, []int{0}
}
func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (dst *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(dst, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Log) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Log) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Log) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *Log) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Log) GetUpdatedOn() int64 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

func (m *Log) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *Log) GetDeletedOn() int64 {
	if m != nil {
		return m.DeletedOn
	}
	return 0
}

func (m *Log) GetDeletedBy() string {
	if m != nil {
		return m.DeletedBy
	}
	return ""
}

func init() {
	proto.RegisterType((*Log)(nil), "log.Log")
	proto.RegisterMapType((map[string]string)(nil), "log.Log.DataEntry")
}

func init() { proto.RegisterFile("log.proto", fileDescriptor_log_7db29dfae25f4450) }

var fileDescriptor_log_7db29dfae25f4450 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4a, 0xc5, 0x30,
	0x14, 0x40, 0x49, 0xd3, 0x56, 0x73, 0x5d, 0xe4, 0xe2, 0x10, 0xc4, 0xa1, 0x38, 0x48, 0xa7, 0x0e,
	0x3a, 0x28, 0x8e, 0x45, 0xb7, 0x82, 0xd0, 0x3f, 0x88, 0x26, 0x04, 0x31, 0x34, 0xa5, 0xa4, 0xf2,
	0xf2, 0x7b, 0xef, 0xcb, 0x1e, 0x49, 0x4a, 0xda, 0xed, 0xe6, 0x1c, 0xce, 0x85, 0x5c, 0x60, 0xc6,
	0xea, 0x6e, 0x5e, 0xac, 0xb3, 0x48, 0x8d, 0xd5, 0x8f, 0xe7, 0x02, 0xe8, 0x60, 0x35, 0x22, 0x94,
	0x7a, 0xfd, 0x95, 0x9c, 0x34, 0xa4, 0x65, 0x63, 0x9c, 0x03, 0x73, 0xea, 0xe4, 0x78, 0x91, 0x58,
	0x98, 0xf1, 0x09, 0x4a, 0x29, 0x9c, 0xe0, 0xb4, 0xa1, 0xed, 0xcd, 0x33, 0x76, 0x61, 0xdd, 0x60,
	0x75, 0xf7, 0x21, 0x9c, 0xf8, 0x9c, 0xdc, 0xe2, 0xc7, 0xe8, 0xf1, 0x01, 0xd8, 0xcf, 0xa2, 0x84,
	0x53, 0xf2, 0x6b, 0xe2, 0x65, 0x43, 0x5a, 0x3a, 0xee, 0xe0, 0x60, 0x7b, 0xcf, 0xab, 0xb8, 0x7e,
	0x07, 0xc1, 0xae, 0xb3, 0xdc, 0xda, 0x3a, 0xb5, 0x19, 0x1c, 0x6c, 0xef, 0xf9, 0x55, 0x6a, 0x33,
	0x08, 0x56, 0x2a, 0xa3, 0x52, 0x7b, 0x9d, 0xda, 0x0c, 0x0e, 0xb6, 0xf7, 0x9c, 0xa5, 0x36, 0x83,
	0xfb, 0x57, 0x60, 0xf9, 0x1b, 0x78, 0x0b, 0xf4, 0x4f, 0xf9, 0xed, 0x1e, 0x61, 0xc4, 0x3b, 0xa8,
	0xfe, 0x85, 0x59, 0xd5, 0x76, 0x8f, 0xf4, 0x78, 0x2f, 0xde, 0xc8, 0x77, 0x1d, 0x0f, 0xfa, 0x72,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x32, 0x21, 0xb3, 0x5d, 0x01, 0x00, 0x00,
}
