// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package log

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Log struct {
	Guid                 string            `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Text                 string            `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedOn            int64             `protobuf:"varint,4,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	CreatedBy            string            `protobuf:"bytes,5,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedOn            int64             `protobuf:"varint,6,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	UpdatedBy            string            `protobuf:"bytes,7,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	DeletedOn            int64             `protobuf:"varint,8,opt,name=deletedOn,proto3" json:"deletedOn,omitempty"`
	DeletedBy            string            `protobuf:"bytes,9,opt,name=deletedBy,proto3" json:"deletedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_448ba679d7207cd1, []int{0}
}
func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (dst *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(dst, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Log) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Log) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Log) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *Log) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Log) GetUpdatedOn() int64 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

func (m *Log) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *Log) GetDeletedOn() int64 {
	if m != nil {
		return m.DeletedOn
	}
	return 0
}

func (m *Log) GetDeletedBy() string {
	if m != nil {
		return m.DeletedBy
	}
	return ""
}

type LogCreateRequest struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	CreatedOn            int64    `protobuf:"varint,3,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	UpdatedOn            int64    `protobuf:"varint,4,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogCreateRequest) Reset()         { *m = LogCreateRequest{} }
func (m *LogCreateRequest) String() string { return proto.CompactTextString(m) }
func (*LogCreateRequest) ProtoMessage()    {}
func (*LogCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_448ba679d7207cd1, []int{1}
}
func (m *LogCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogCreateRequest.Unmarshal(m, b)
}
func (m *LogCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogCreateRequest.Marshal(b, m, deterministic)
}
func (dst *LogCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogCreateRequest.Merge(dst, src)
}
func (m *LogCreateRequest) XXX_Size() int {
	return xxx_messageInfo_LogCreateRequest.Size(m)
}
func (m *LogCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogCreateRequest proto.InternalMessageInfo

func (m *LogCreateRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *LogCreateRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *LogCreateRequest) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *LogCreateRequest) GetUpdatedOn() int64 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

type LogCreateResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Log                  *Log     `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogCreateResponse) Reset()         { *m = LogCreateResponse{} }
func (m *LogCreateResponse) String() string { return proto.CompactTextString(m) }
func (*LogCreateResponse) ProtoMessage()    {}
func (*LogCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_448ba679d7207cd1, []int{2}
}
func (m *LogCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogCreateResponse.Unmarshal(m, b)
}
func (m *LogCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogCreateResponse.Marshal(b, m, deterministic)
}
func (dst *LogCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogCreateResponse.Merge(dst, src)
}
func (m *LogCreateResponse) XXX_Size() int {
	return xxx_messageInfo_LogCreateResponse.Size(m)
}
func (m *LogCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogCreateResponse proto.InternalMessageInfo

func (m *LogCreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LogCreateResponse) GetLog() *Log {
	if m != nil {
		return m.Log
	}
	return nil
}

func init() {
	proto.RegisterType((*Log)(nil), "log.Log")
	proto.RegisterMapType((map[string]string)(nil), "log.Log.DataEntry")
	proto.RegisterType((*LogCreateRequest)(nil), "log.LogCreateRequest")
	proto.RegisterType((*LogCreateResponse)(nil), "log.LogCreateResponse")
}

func init() { proto.RegisterFile("log.proto", fileDescriptor_log_448ba679d7207cd1) }

var fileDescriptor_log_448ba679d7207cd1 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x36, 0xad, 0xcd, 0x14, 0xa4, 0x0e, 0x2a, 0x4b, 0xf1, 0x50, 0x7a, 0x90, 0x9e,
	0x7a, 0xa8, 0x87, 0x8a, 0x17, 0xa1, 0xda, 0x5b, 0x40, 0x88, 0x4f, 0xb0, 0x76, 0x87, 0xa5, 0x18,
	0xba, 0x35, 0xdd, 0x14, 0xf3, 0x7a, 0x3e, 0x99, 0xec, 0x6e, 0xbb, 0x49, 0x8b, 0x07, 0x6f, 0x93,
	0xef, 0xcf, 0x3f, 0xc3, 0xfc, 0xb3, 0x90, 0x16, 0x5a, 0x4d, 0xb7, 0xa5, 0x36, 0x1a, 0x59, 0xa1,
	0xd5, 0xf8, 0x27, 0x06, 0x96, 0x69, 0x85, 0x08, 0x89, 0xaa, 0xd6, 0x92, 0x47, 0xa3, 0x68, 0x92,
	0xe6, 0xae, 0xb6, 0xcc, 0xd0, 0xb7, 0xe1, 0xb1, 0x67, 0xb6, 0xc6, 0x7b, 0x48, 0xa4, 0x30, 0x82,
	0xb3, 0x11, 0x9b, 0xf4, 0x67, 0x38, 0xb5, 0xed, 0x32, 0xad, 0xa6, 0xaf, 0xc2, 0x88, 0xe5, 0xc6,
	0x94, 0x75, 0xee, 0x74, 0xbc, 0x83, 0x74, 0x55, 0x92, 0x30, 0x24, 0xdf, 0x36, 0x3c, 0x19, 0x45,
	0x13, 0x96, 0x37, 0xa0, 0xa5, 0x2e, 0x6a, 0xde, 0x71, 0xed, 0x1b, 0x60, 0xd5, 0x6a, 0x2b, 0x0f,
	0xde, 0xae, 0xf7, 0x06, 0xd0, 0x52, 0x17, 0x35, 0xbf, 0xf0, 0xde, 0x00, 0xac, 0x2a, 0xa9, 0x20,
	0xef, 0xed, 0x79, 0x6f, 0x00, 0x2d, 0x75, 0x51, 0xf3, 0xd4, 0x7b, 0x03, 0x18, 0xce, 0x21, 0x0d,
	0x6b, 0xe0, 0x00, 0xd8, 0x27, 0xd5, 0x87, 0x3c, 0x6c, 0x89, 0xd7, 0xd0, 0xd9, 0x8b, 0xa2, 0xa2,
	0x43, 0x1e, 0xfe, 0xe3, 0x29, 0x7e, 0x8c, 0xc6, 0x7b, 0x18, 0x64, 0x5a, 0xbd, 0xb8, 0x05, 0x72,
	0xfa, 0xaa, 0x68, 0x67, 0xfe, 0x1d, 0xe8, 0x49, 0x50, 0xec, 0x8f, 0xa0, 0x9a, 0x28, 0x92, 0xb3,
	0x28, 0xc6, 0xcf, 0x70, 0xd5, 0x9a, 0xbb, 0xdb, 0xea, 0xcd, 0x8e, 0xf0, 0x12, 0xe2, 0x30, 0x36,
	0x5e, 0x4b, 0x1c, 0x82, 0x3d, 0xb4, 0x9b, 0xd9, 0x9f, 0xf5, 0x8e, 0x07, 0xcb, 0x2d, 0x9c, 0x2d,
	0x01, 0x32, 0xad, 0xde, 0xa9, 0xdc, 0xaf, 0x57, 0x84, 0x73, 0xe8, 0xfa, 0x5e, 0x78, 0x73, 0xfc,
	0xed, 0x64, 0xa7, 0xe1, 0xed, 0x39, 0xf6, 0x23, 0x3f, 0xba, 0xee, 0x41, 0x3d, 0xfc, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x7f, 0x9f, 0x8a, 0xee, 0x5d, 0x02, 0x00, 0x00,
}
