// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log_group.proto

package log

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogGroup struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Log                  []*Log   `protobuf:"bytes,2,rep,name=log,proto3" json:"log,omitempty"`
	CreatedOn            int64    `protobuf:"varint,3,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	CreatedBy            string   `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedOn            int64    `protobuf:"varint,5,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,6,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogGroup) Reset()         { *m = LogGroup{} }
func (m *LogGroup) String() string { return proto.CompactTextString(m) }
func (*LogGroup) ProtoMessage()    {}
func (*LogGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_log_group_e71ab2af845a089f, []int{0}
}
func (m *LogGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogGroup.Unmarshal(m, b)
}
func (m *LogGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogGroup.Marshal(b, m, deterministic)
}
func (dst *LogGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogGroup.Merge(dst, src)
}
func (m *LogGroup) XXX_Size() int {
	return xxx_messageInfo_LogGroup.Size(m)
}
func (m *LogGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_LogGroup.DiscardUnknown(m)
}

var xxx_messageInfo_LogGroup proto.InternalMessageInfo

func (m *LogGroup) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *LogGroup) GetLog() []*Log {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *LogGroup) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *LogGroup) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *LogGroup) GetUpdatedOn() int64 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

func (m *LogGroup) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func init() {
	proto.RegisterType((*LogGroup)(nil), "log.LogGroup")
}

func init() { proto.RegisterFile("log_group.proto", fileDescriptor_log_group_e71ab2af845a089f) }

var fileDescriptor_log_group_e71ab2af845a089f = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0xc9, 0x4f, 0x8f,
	0x4f, 0x2f, 0xca, 0x2f, 0x2d, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0xc9, 0x4f,
	0x97, 0xe2, 0xcc, 0xc9, 0x4f, 0x87, 0xf0, 0x95, 0x36, 0x31, 0x72, 0x71, 0xf8, 0xe4, 0xa7, 0xbb,
	0x83, 0x94, 0x08, 0x09, 0x71, 0xb1, 0xa4, 0x97, 0x66, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70,
	0x06, 0x81, 0xd9, 0x42, 0x52, 0x5c, 0x20, 0x2d, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x1c,
	0x7a, 0x20, 0x9d, 0x3e, 0xf9, 0xe9, 0x41, 0x20, 0x41, 0x21, 0x19, 0x2e, 0xce, 0xe4, 0xa2, 0xd4,
	0xc4, 0x92, 0xd4, 0x14, 0xff, 0x3c, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x84, 0x00, 0x92,
	0xac, 0x53, 0xa5, 0x04, 0x0b, 0xd8, 0x48, 0x84, 0x00, 0x48, 0xb6, 0xb4, 0x20, 0x05, 0xaa, 0x97,
	0x15, 0xa2, 0x17, 0x2e, 0x80, 0x24, 0xeb, 0x54, 0x29, 0xc1, 0x06, 0xd1, 0x0b, 0x17, 0x48, 0x62,
	0x03, 0xbb, 0xdd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x54, 0xd5, 0x5b, 0x9c, 0xde, 0x00, 0x00,
	0x00,
}
