#!/bin/bash

set -euo pipefail

if [ -z "${1:-}" ]; then
  echo "Usage: $0 <service>"
  exit 1
elif [ -z "${REMOTE_SERVER:-}" ] || [ -z "${REMOTE_APP_DIR:-}" ]; then
  echo "A value for \$REMOTE_SERVER and \$REMOTE_APP_DIR are required"
  exit 1
fi

remote_server="$REMOTE_SERVER"
remote_app_dir="$REMOTE_APP_DIR"

service="$1"
image="minond/captainslog-$service"
container="cl-$service"

remote-exec() {
  local cmd="$1"
  echo
  echo "=> $cmd"
  ssh "$remote_server" "$cmd"
}

case "$service" in
  processor|web|worker)
    echo "Deploying $service (container: $container, image: $image)"

    remote-exec "docker pull $image:latest"
    remote-exec "docker stop $container"
    remote-exec "docker rm $container"

    case "$service" in
      processor) remote-exec "docker run -d --env-file $remote_app_dir/.env --name cl-$service -p 8081:8081 $image" ;;
      web) remote-exec "docker run -d --env-file $remote_app_dir/.env --name cl-$service -p 3007:3000 $image" ;;
      worker) remote-exec "docker run -d --env-file $remote_app_dir/.env --name cl-worker $image" ;;
    esac

    echo
    echo "Done deploying $service"

    ;;

  *)
    echo "Invalid service: $service"
    exit 1
    ;;
esac
