#!/bin/bash

set -euo pipefail

log() {
  local label="$1"
  local message="$2"
  echo "$label: $message"
}

new_book() {
  local name="$1"
  local grouping="$2"

  data="{\"name\": \"$name\", \"grouping\": $grouping}"
  resp=$(curl -s -X POST http://localhost/api/books -d "$data")

  echo "$resp" | jq '.guid' -r
}

new_extractor() {
  local label="$1"
  local match="$2"
  local book_guid="$3"

  data="{\"bookGuid\": \"$book_guid\", \"label\": \"$label\", \"match\": \"$match\"}"
  resp=$(curl -s -X POST http://localhost/api/extractors -d "$data")

  echo "$resp" | jq '.guid' -r
}

new_shorthand() {
  local expansion="$1"
  local match="$2"
  local text="$3"
  local book_guid="$4"

  data="{\"bookGuid\": \"$book_guid\", \"expansion\": \"$expansion\", \"match\": \"$match\", \"text\": \"$text\"}"
  resp=$(curl -s -X POST http://localhost/api/shorthands -d "$data")

  echo "$resp" | jq '.guid' -r
}

new_entry() {
  local text="$1"
  local book_guid="$2"
  local created_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

  data="{\"guid\": \"$RANDOM\", \"bookGuid\": \"$book_guid\", \"text\": \"$text\", \"createdAt\": \"$created_at\"}"
  resp=$(curl -s -X POST http://localhost/api/entries -d "$data")

  echo "$resp" | jq '.entry.guid' -r
}

reset_db() {
  cleaner="truncate books; truncate collections; truncate entries; truncate extractors; truncate shorthands;"
  psql captainslog --dbname captainslog -c "$cleaner" &> /dev/null
  log "db" "reset"
}

create_workouts() {
  workouts=$(new_book "Workouts" 1)
  log "new book" "$workouts"

  (log "new extractor" $(new_extractor "exercise" '^(.+),' "$workouts")) &
  (log "new extractor" $(new_extractor "sets" ',\\s{0,}(\\d+)\\s{0,}x' "$workouts")) &
  (log "new extractor" $(new_extractor "reps" '\\dx\\s{0,}(\\d+)' "$workouts")) &
  (log "new extractor" $(new_extractor "weight" '@\\s{0,}(\\d+(\\.\\d{1,2})?)$' "$workouts")) &
  (log "new extractor" $(new_extractor "time"      '(\\d+)\\s{0,}(sec|seconds|min|minutes|hour|hours)' "$workouts")) &
  (log "new extractor" $(new_extractor "time_unit" '\\d+\\s{0,}(sec|seconds|min|minutes|hour|hours)' "$workouts")) &
  (log "new extractor" $(new_extractor "distance"      '(\\d+)\\s{0,}(miles|k|kilometers)' "$workouts")) &
  (log "new extractor" $(new_extractor "distance_unit" '\\d+\\s{0,}(miles|k|kilometers)' "$workouts")) &

  (log "new shorthand" $(new_shorthand "xx @ " "" "xx " "$workouts")) &
  (log "new shorthand" $(new_shorthand "3x10" "" "xxx" "$workouts")) &
  (log "new shorthand" $(new_shorthand "2x10" "" "xx" "$workouts")) &

  wait

  (log "new entry" $(new_entry "Bench press, xxx@65" "$workouts")) &
  (log "new entry" $(new_entry "Squats, 2min" "$workouts")) &
  (log "new entry" $(new_entry "Squats, xxx@45" "$workouts")) &
  (log "new entry" $(new_entry "Running, 30min" "$workouts")) &

  wait
}

create_blood_pressure() {
  blood_pressure=$(new_book "Blood Pressure" 0)
  log "new book" "$blood_pressure"

  (log "new extractor" $(new_extractor "a" '^(\\d+)\\s{0,}/' "$blood_pressure")) &
  (log "new extractor" $(new_extractor "b" '/\\s{0,}(\\d+)\\s' "$blood_pressure")) &
  (log "new extractor" $(new_extractor "pulse" '\\(pulse (\\d+)\\)' "$blood_pressure")) &

  wait

  (log "new entry" $(new_entry "121 / 73 (pulse 67)" "$blood_pressure")) &
  (log "new entry" $(new_entry "122 / 88 (pulse 80)" "$blood_pressure")) &
  (log "new entry" $(new_entry "126 / 84 (pulse 101)" "$blood_pressure")) &
  (log "new entry" $(new_entry "127 / 81 (pulse 85)" "$blood_pressure")) &
  (log "new entry" $(new_entry "129 / 81 (pulse 89)" "$blood_pressure")) &
  (log "new entry" $(new_entry "132 / 87 (pulse 74)" "$blood_pressure")) &
  (log "new entry" $(new_entry "133 / 84 (pulse 80)" "$blood_pressure")) &
  (log "new entry" $(new_entry "133 / 90 (pulse 83)" "$blood_pressure")) &
  (log "new entry" $(new_entry "136 / 84 (pulse 76)" "$blood_pressure")) &

  wait
}

reset_db
create_workouts &
create_blood_pressure &

wait
echo done
