#!/bin/bash

set -euo pipefail

log() {
  local label="$1"
  local message="$2"
  echo "$label: $message"
}

new_book() {
  local name="$1"
  local grouping="$2"

  data="{\"name\": \"$name\", \"grouping\": $grouping}"
  resp=$(curl -s -X POST http://localhost/api/book -d "$data")

  echo "$resp" | jq '.guid' -r
}

new_extractor() {
  local label="$1"
  local match="$2"
  local book_guid="$3"

  data="{\"bookGuid\": \"$book_guid\", \"label\": \"$label\", \"match\": \"$match\"}"
  resp=$(curl -s -X POST http://localhost/api/extractor -d "$data")

  echo "$resp" | jq '.guid' -r
}

new_shorthand() {
  local expansion="$1"
  local match="$2"
  local text="$3"
  local book_guid="$4"

  data="{\"bookGuid\": \"$book_guid\", \"expansion\": \"$expansion\", \"match\": \"$match\", \"text\": \"$text\"}"
  resp=$(curl -s -X POST http://localhost/api/shorthand -d "$data")

  echo "$resp" | jq '.guid' -r
}

new_entry() {
  local text="$1"
  local book_guid="$2"

  data="{\"guid\": \"$RANDOM\", \"bookGuid\": \"$book_guid\", \"text\": \"$text\"}"
  resp=$(curl -s -X POST http://localhost/api/entry -d "$data")

  echo "$resp" | jq '.entry.guid' -r
}

cleaner="truncate books; truncate collections; truncate entries; truncate extractors; truncate shorthands;"
psql captainslog --dbname captainslog -c "$cleaner" &> /dev/null
log "db" "reset"

workouts=$(new_book "Workouts" 1)
log "new book" "$workouts"

log "new extractor" $(new_extractor "exercise" '^(.+),' "$workouts")
log "new extractor" $(new_extractor "sets" ',\\s{0,}(\\d+)\\s{0,}x' "$workouts")
log "new extractor" $(new_extractor "reps" '\\dx\\s{0,}(\\d+)' "$workouts")
log "new extractor" $(new_extractor "weight" '@\\s{0,}(\\d+)$' "$workouts")
log "new extractor" $(new_extractor "time" '(\\d+)\\s{0,}(sec|seconds|min|minutes|hour|hours)' "$workouts")
log "new extractor" $(new_extractor "unit" '\\d+\\s{0,}(sec|seconds|min|minutes|hour|hours)' "$workouts")

log "new shorthand" $(new_shorthand "3x10" "" "xxx" "$workouts")

log "new entry" $(new_entry "Bench press, 3x10@65" "$workouts")
log "new entry" $(new_entry "Squats, 2min" "$workouts")
log "new entry" $(new_entry "Squats, 3x10@45" "$workouts")
log "new entry" $(new_entry "Running, 30min" "$workouts")

# curl "http://localhost/api/entry?book=$workouts" | jq ''

blood_pressure=$(new_book "Blood Pressure" 0)
log "new book" "$blood_pressure"

log "new extractor" $(new_extractor "a" '^(\\d+)\\s{0,}/' "$blood_pressure")
log "new extractor" $(new_extractor "b" '/\\s{0,}(\\d+)\\s' "$blood_pressure")
log "new extractor" $(new_extractor "pulse" '\\(pulse (\\d+)\\)' "$blood_pressure")

log "new entry" $(new_entry "121 / 73 (pulse 67)" "$blood_pressure")
log "new entry" $(new_entry "122 / 88 (pulse 80)" "$blood_pressure")
log "new entry" $(new_entry "126 / 84 (pulse 101)" "$blood_pressure")
log "new entry" $(new_entry "127 / 81 (pulse 85)" "$blood_pressure")
log "new entry" $(new_entry "129 / 81 (pulse 89)" "$blood_pressure")
log "new entry" $(new_entry "132 / 87 (pulse 74)" "$blood_pressure")
log "new entry" $(new_entry "133 / 84 (pulse 80)" "$blood_pressure")
log "new entry" $(new_entry "133 / 90 (pulse 83)" "$blood_pressure")
log "new entry" $(new_entry "136 / 84 (pulse 76)" "$blood_pressure")

# curl "http://localhost/api/entry?book=$blood_pressure" | jq ''
