// Code generated by "stringer -type=Tok"; DO NOT EDIT.

package query

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokInvalid-0]
	_ = x[tokEof-1]
	_ = x[tokCloseParenthesis-2]
	_ = x[tokComma-3]
	_ = x[tokDiv-4]
	_ = x[tokEq-5]
	_ = x[tokGe-6]
	_ = x[tokGt-7]
	_ = x[tokLe-8]
	_ = x[tokLt-9]
	_ = x[tokMinus-10]
	_ = x[tokMul-11]
	_ = x[tokOpenParenthesis-12]
	_ = x[tokPeriod-13]
	_ = x[tokPlus-14]
	_ = x[tokDoubleQuoteString-15]
	_ = x[tokIdentifier-16]
	_ = x[tokNumber-17]
	_ = x[tokSingleQuoteString-18]
}

const _Tok_name = "tokInvalidtokEoftokCloseParenthesistokCommatokDivtokEqtokGetokGttokLetokLttokMinustokMultokOpenParenthesistokPeriodtokPlustokDoubleQuoteStringtokIdentifiertokNumbertokSingleQuoteString"

var _Tok_index = [...]uint8{0, 10, 16, 35, 43, 49, 54, 59, 64, 69, 74, 82, 88, 106, 115, 122, 142, 155, 164, 184}

func (i Tok) String() string {
	if i >= Tok(len(_Tok_index)-1) {
		return "Tok(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tok_name[_Tok_index[i]:_Tok_index[i+1]]
}
