// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collection.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Collection struct {
	Entry                []*Entry `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_collection_ef423fd2a0597e5e, []int{0}
}
func (m *Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collection.Unmarshal(m, b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
}
func (dst *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(dst, src)
}
func (m *Collection) XXX_Size() int {
	return xxx_messageInfo_Collection.Size(m)
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetEntry() []*Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func init() {
	proto.RegisterType((*Collection)(nil), "captainslog.Collection")
}

func init() { proto.RegisterFile("collection.proto", fileDescriptor_collection_ef423fd2a0597e5e) }

var fileDescriptor_collection_ef423fd2a0597e5e = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0xcf, 0xc9,
	0x49, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4e,
	0x2c, 0x28, 0x49, 0xcc, 0xcc, 0x2b, 0xce, 0xc9, 0x4f, 0x97, 0xe2, 0x4e, 0xcd, 0x2b, 0x29, 0xaa,
	0x84, 0xc8, 0x28, 0x99, 0x71, 0x71, 0x39, 0xc3, 0x55, 0x0b, 0x69, 0x70, 0xb1, 0x82, 0x25, 0x25,
	0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x84, 0xf4, 0x90, 0xf4, 0xe9, 0xb9, 0x82, 0x64, 0x82, 0x20,
	0x0a, 0x9c, 0xd8, 0xa3, 0x58, 0xc1, 0x06, 0x24, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x9f, 0x77, 0x93, 0x58, 0x75, 0x00, 0x00, 0x00,
}
