// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collection.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Collection struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Entry                []*Entry `protobuf:"bytes,2,rep,name=entry,proto3" json:"entry,omitempty"`
	CreatedOn            int64    `protobuf:"varint,3,opt,name=createdOn,proto3" json:"createdOn,omitempty"`
	CreatedBy            string   `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedOn            int64    `protobuf:"varint,5,opt,name=updatedOn,proto3" json:"updatedOn,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,6,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_collection_8e42c96e062dd96b, []int{0}
}
func (m *Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collection.Unmarshal(m, b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
}
func (dst *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(dst, src)
}
func (m *Collection) XXX_Size() int {
	return xxx_messageInfo_Collection.Size(m)
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Collection) GetEntry() []*Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *Collection) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *Collection) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Collection) GetUpdatedOn() int64 {
	if m != nil {
		return m.UpdatedOn
	}
	return 0
}

func (m *Collection) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func init() {
	proto.RegisterType((*Collection)(nil), "captainslog.Collection")
}

func init() { proto.RegisterFile("collection.proto", fileDescriptor_collection_8e42c96e062dd96b) }

var fileDescriptor_collection_8e42c96e062dd96b = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0xcf, 0xc9,
	0x49, 0x4d, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4e,
	0x2c, 0x28, 0x49, 0xcc, 0xcc, 0x2b, 0xce, 0xc9, 0x4f, 0x97, 0xe2, 0x4e, 0xcd, 0x2b, 0x29, 0xaa,
	0x84, 0xc8, 0x28, 0x1d, 0x62, 0xe4, 0xe2, 0x72, 0x86, 0x2b, 0x17, 0x12, 0xe2, 0x62, 0x49, 0x2f,
	0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x34, 0xb8, 0x58, 0xc1,
	0x3a, 0x24, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0x84, 0xf4, 0x90, 0x0c, 0xd3, 0x73, 0x05, 0xc9,
	0x04, 0x41, 0x14, 0x08, 0xc9, 0x70, 0x71, 0x26, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0xa6, 0xf8, 0xe7,
	0x49, 0x30, 0x2b, 0x30, 0x6a, 0x30, 0x07, 0x21, 0x04, 0x90, 0x64, 0x9d, 0x2a, 0x25, 0x58, 0xc0,
	0x16, 0x20, 0x04, 0x40, 0xb2, 0xa5, 0x05, 0x29, 0x50, 0xbd, 0xac, 0x10, 0xbd, 0x70, 0x01, 0x24,
	0x59, 0xa7, 0x4a, 0x09, 0x36, 0x88, 0x5e, 0xb8, 0x80, 0x13, 0x7b, 0x14, 0x2b, 0xd8, 0x37, 0x49,
	0x6c, 0x60, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xf4, 0xd5, 0xe4, 0x02, 0x01, 0x00,
	0x00,
}
