// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entry.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entry struct {
	Guid                 string            `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Text                 string            `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_a122601ee1565ed7, []int{0}
}
func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (dst *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(dst, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Entry) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Entry) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type EntryCreateRequest struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	BookGuid             string   `protobuf:"bytes,3,opt,name=book_guid,json=bookGuid,proto3" json:"book_guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryCreateRequest) Reset()         { *m = EntryCreateRequest{} }
func (m *EntryCreateRequest) String() string { return proto.CompactTextString(m) }
func (*EntryCreateRequest) ProtoMessage()    {}
func (*EntryCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_a122601ee1565ed7, []int{1}
}
func (m *EntryCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryCreateRequest.Unmarshal(m, b)
}
func (m *EntryCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryCreateRequest.Marshal(b, m, deterministic)
}
func (dst *EntryCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryCreateRequest.Merge(dst, src)
}
func (m *EntryCreateRequest) XXX_Size() int {
	return xxx_messageInfo_EntryCreateRequest.Size(m)
}
func (m *EntryCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EntryCreateRequest proto.InternalMessageInfo

func (m *EntryCreateRequest) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *EntryCreateRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *EntryCreateRequest) GetBookGuid() string {
	if m != nil {
		return m.BookGuid
	}
	return ""
}

type EntryCreateResponse struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Entry                *Entry   `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntryCreateResponse) Reset()         { *m = EntryCreateResponse{} }
func (m *EntryCreateResponse) String() string { return proto.CompactTextString(m) }
func (*EntryCreateResponse) ProtoMessage()    {}
func (*EntryCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_a122601ee1565ed7, []int{2}
}
func (m *EntryCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntryCreateResponse.Unmarshal(m, b)
}
func (m *EntryCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntryCreateResponse.Marshal(b, m, deterministic)
}
func (dst *EntryCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntryCreateResponse.Merge(dst, src)
}
func (m *EntryCreateResponse) XXX_Size() int {
	return xxx_messageInfo_EntryCreateResponse.Size(m)
}
func (m *EntryCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EntryCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EntryCreateResponse proto.InternalMessageInfo

func (m *EntryCreateResponse) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *EntryCreateResponse) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func init() {
	proto.RegisterType((*Entry)(nil), "captainslog.Entry")
	proto.RegisterMapType((map[string]string)(nil), "captainslog.Entry.DataEntry")
	proto.RegisterType((*EntryCreateRequest)(nil), "captainslog.EntryCreateRequest")
	proto.RegisterType((*EntryCreateResponse)(nil), "captainslog.EntryCreateResponse")
}

func init() { proto.RegisterFile("entry.proto", fileDescriptor_entry_a122601ee1565ed7) }

var fileDescriptor_entry_a122601ee1565ed7 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcd, 0x2b, 0x29,
	0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4e, 0x2c, 0x28, 0x49, 0xcc, 0xcc,
	0x2b, 0xce, 0xc9, 0x4f, 0x57, 0x9a, 0xc5, 0xc8, 0xc5, 0xea, 0x0a, 0x92, 0x14, 0x12, 0xe2, 0x62,
	0x49, 0x2f, 0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x41, 0x62, 0x25,
	0xa9, 0x15, 0x25, 0x12, 0x4c, 0x10, 0x31, 0x10, 0x5b, 0xc8, 0x80, 0x8b, 0x25, 0x25, 0xb1, 0x24,
	0x51, 0x82, 0x59, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x46, 0x0f, 0xc9, 0x34, 0x3d, 0xb0, 0x49, 0x7a,
	0x2e, 0x89, 0x25, 0x89, 0x60, 0x56, 0x10, 0x58, 0xa5, 0x94, 0x39, 0x17, 0x27, 0x5c, 0x48, 0x48,
	0x80, 0x8b, 0x39, 0x3b, 0xb5, 0x12, 0x6a, 0x0b, 0x88, 0x29, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98,
	0x53, 0x9a, 0x0a, 0xb5, 0x05, 0xc2, 0xb1, 0x62, 0xb2, 0x60, 0x54, 0x8a, 0xe4, 0x12, 0x02, 0x6b,
	0x72, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x21, 0xda, 0xa1,
	0xd2, 0x5c, 0x9c, 0x49, 0xf9, 0xf9, 0xd9, 0xf1, 0x60, 0xc5, 0xcc, 0x60, 0x09, 0x0e, 0x90, 0x80,
	0x7b, 0x69, 0x66, 0x8a, 0x52, 0x30, 0x97, 0x30, 0x8a, 0xd1, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9,
	0x58, 0xcd, 0xd6, 0xe0, 0x62, 0x05, 0x07, 0x1f, 0xd8, 0x70, 0x6e, 0x23, 0x21, 0x4c, 0x1f, 0x07,
	0x41, 0x14, 0x38, 0xb1, 0x47, 0xb1, 0x82, 0x83, 0x38, 0x89, 0x0d, 0x4c, 0x19, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xba, 0xd4, 0xde, 0x8e, 0x78, 0x01, 0x00, 0x00,
}
