// Code generated by protoc-gen-go. DO NOT EDIT.
// source: extractor.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Extractor struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Match                string   `protobuf:"bytes,3,opt,name=match,proto3" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Extractor) Reset()         { *m = Extractor{} }
func (m *Extractor) String() string { return proto.CompactTextString(m) }
func (*Extractor) ProtoMessage()    {}
func (*Extractor) Descriptor() ([]byte, []int) {
	return fileDescriptor_extractor_d627ef8d1172e9fd, []int{0}
}
func (m *Extractor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Extractor.Unmarshal(m, b)
}
func (m *Extractor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Extractor.Marshal(b, m, deterministic)
}
func (dst *Extractor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Extractor.Merge(dst, src)
}
func (m *Extractor) XXX_Size() int {
	return xxx_messageInfo_Extractor.Size(m)
}
func (m *Extractor) XXX_DiscardUnknown() {
	xxx_messageInfo_Extractor.DiscardUnknown(m)
}

var xxx_messageInfo_Extractor proto.InternalMessageInfo

func (m *Extractor) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *Extractor) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Extractor) GetMatch() string {
	if m != nil {
		return m.Match
	}
	return ""
}

func init() {
	proto.RegisterType((*Extractor)(nil), "captainslog.Extractor")
}

func init() { proto.RegisterFile("extractor.proto", fileDescriptor_extractor_d627ef8d1172e9fd) }

var fileDescriptor_extractor_d627ef8d1172e9fd = []byte{
	// 116 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xad, 0x28, 0x29,
	0x4a, 0x4c, 0x2e, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4e, 0x2c,
	0x28, 0x49, 0xcc, 0xcc, 0x2b, 0xce, 0xc9, 0x4f, 0x57, 0xf2, 0xe6, 0xe2, 0x74, 0x85, 0xc9, 0x0b,
	0x09, 0x71, 0xb1, 0xa4, 0x97, 0x66, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9,
	0x42, 0x22, 0x5c, 0xac, 0x39, 0x89, 0x49, 0xa9, 0x39, 0x12, 0x4c, 0x60, 0x41, 0x08, 0x07, 0x24,
	0x9a, 0x9b, 0x58, 0x92, 0x9c, 0x21, 0xc1, 0x0c, 0x11, 0x05, 0x73, 0x9c, 0xd8, 0xa3, 0x58, 0xc1,
	0x56, 0x24, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x2d, 0xe7, 0x98,
	0x7c, 0x00, 0x00, 0x00,
}
