FROM minond/captainslog-ruby

ENV RAILS_SERVE_STATIC_FILES true
ENV RAILS_LOG_TO_STDOUT true

RUN apt-get update \
      && apt-get install -y nodejs npm \
      && npm install

RUN bundle exec rake assets:clobber \
      && bundle exec rake assets:precompile \
      && bundle exec rake ts:compile

EXPOSE 3000

CMD ["bundle", "exec", "./bin/rails", "server", "-b", "0.0.0.0"]
