FROM minond/captainslog-web-base

ENV RAILS_SERVE_STATIC_FILES true
ENV RAILS_LOG_TO_STDOUT true

EXPOSE 3000

CMD ["bundle", "exec", "./bin/rails", "server", "-b", "0.0.0.0"]

COPY web/app/client/ app/client/
COPY web/tsconfig.json .
RUN npm run build

COPY web .
RUN bundle exec rake assets:precompile
