source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "bcrypt", "~> 3.1.7"                      # Use Active Model has_secure_password
gem "bootsnap", ">= 1.4.2", :require => false # Reduces boot times through caching; required in config/boot.rb
gem "daemons"                                 # Provides an easy way to wrap ruby scripts to be run as a daemon. Needed by Delayed Job
gem "delayed_job"                             # Database based asynchronous priority queue system
gem "delayed_job_active_record"               # AR bindings for Delayed Job
gem "devise"                                  # Flexible authentication solution for Rails with Warden.
gem "fast_attributes"                         # FastAttributes adds attributes with their types to the class
gem "fitbit_api"                              # Fitbit API client
gem "jaeger-client"                           # OpenTracing Tracer implementation for Jaeger in Ruby
gem "jbuilder", "~> 2.7"                      # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jquery-rails"                            # A gem to automate using jQuery with Rails
gem "jwt"                                     # JSON Web Token encoder/decoder
gem "lastfm"                                  # A Ruby interface for Last.fm Web Services
gem "opentracing"                             # OpenTracing API for Ruby
gem "pg", ">= 0.18", "< 2.0"                  # Use postgresql as the database for Active Record
gem "puma", "~> 4.1"                          # Use Puma as the app server
gem "rabl"                                    # JSON view builder
gem "rails", "~> 6.0.1"                       # Bundle edge Rails instead: gem "rails", github: "rails/rails"
gem "simple_command"                          # A simple, standardized way to build and use Service Objects (aka Commands) in Ruby
gem "turbolinks", "~> 5"                      # Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem "tzinfo-data", :platforms => %i[mingw mswin x64_mingw jruby] # Windows does not include zoneinfo files, so bundle the tzinfo-data gem

group :development, :test do
  gem "byebug", :platforms => %i[mri mingw x64_mingw] # Call "byebug" anywhere in the code to stop execution and get a debugger console
end

group :development do
  gem "brakeman"                              # A static analysis security vulnerability scanner for Ruby on Rails applications
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "rails_best_practices"                  # A code metric tool for Rails projects
  gem "reek"                                  # Code smell detector for Ruby
  gem "rubocop", :require => false            # Static code analyzer and code formatter
  gem "sandi_meter"                           # Static analysis tool for checking Ruby code for Sandi Metz' rules.
  gem "spring"                                # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "web-console", ">= 3.3.0"               # Access an interactive console on exception pages or by calling "console" anywhere in the code.
  gem "yard"                                  # Documentation generator
end

group :test do
  gem "capybara", ">= 2.15"                   # Adds support for Capybara system testing and selenium driver
  gem "factory_bot"                           # A library for setting up Ruby objects as test data
  gem "factory_bot_rails"                     # Provides Rails integration for factory_bot
  gem "selenium-webdriver"
  gem "simplecov"                             # Code coverage for Ruby 1.9+ with a powerful configuration library and automatic merging of coverage across test suites
  gem "webdrivers"                            # Easy installation and use of web drivers to run system tests with browsers
end
