require_relative "config/application"

require "rubocop/rake_task"

Rails.application.load_tasks

RuboCop::RakeTask.new

task :lint, [*Rake.application[:rubocop].arg_names] => %i[rubocop reek]

namespace :lint do
  task :all => %i[rubocop sandi_meter rails_best_practices brakeman reek]
end

task :docs do
  `mmdc -i docs/entry_processing_flow.mmd -o docs/entry_processing_flow.svg`
  `mmdc -i docs/entry_querying_flow.mmd -o docs/entry_querying_flow.svg`
end
