require_relative "config/application"

require "rubocop/rake_task"

Rails.application.load_tasks

RuboCop::RakeTask.new

task :lint, [*Rake.application[:rubocop].arg_names] => %i[rubocop reek]

namespace :lint do
  task :all => %i[lint sandi_meter rails_best_practices brakeman]
end
